apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-umr3ag7uw816f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-umr3ag7uw816f
    app.kubernetes.io/part-of: test-metric-utaok79ni7kz5
  name: component-umr3ag7uw816f
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-umr3ag7uw816f
status:
  loadBalancer: {}
